name: py-kaos-utils
version: 0.2.0-sandbox1
description: Set of utilities and helpers for rapid development of Python applications

repo_url: https://github.com/kaoslabsinc/py-kaos-utils
project_url: https://github.com/kaoslabsinc/py-kaos-utils
keywords: python, rapid developments, utils, utilities, helpers, kaos
